# The base URL of the site; the only required configuration variable.
base_url = "https://amiraref.github.io"

# The site title and description; used in feeds by default.
title = "Amir Aref's Blog"
description = "a place to write something that i think would be useful."

# The default site author.
author = "amiraref"

# The default language; used in feeds.

generate_feed = true
compile_sass = true
minify_html = true
build_search_index = true
default_language = "en"

taxonomies = [{name = "tags", feed = true}]

theme = "tabi"

feed_filename = "rss.xml"

[search]
# Whether to include the title of the page/section in the index.
include_title = true
# Whether to include the description of the page/section in the index.
include_description = true
# Whether to include the path of the page/section in the index.
include_path = true
# Whether to include the rendered content of the page/section in the index.
include_content = true
# At which character to truncate the content to. Useful if you have a lot of pages and the index would
# become too big to load on the site. Defaults to not being set.
# truncate_content_length = 100
# Wether to produce the search index as a javascript file or as a JSON file.
# Accepted value "elasticlunr_javascript" or "elasticlunr_json".
index_format = "elasticlunr_json"

[markdown]
highlight_code = true
highlight_theme = "base16-ocean-dark"
smart_punctuation = true

# The Kita theme style config.
[extra]
# Enable KaTex math formula support globally.
math = true
# Enable mermaid support globally.
mermaid = false
# Enable comment support globally.
comment = false


# Enable JavaScript theme toggler to allow users to switch between dark/light mode.
# If disabled, your site will only use the theme specified in the `default_theme` variable.
theme_switcher = true

# This setting determines the default theme on load ("light" or "dark").
# To default to the user's OS-level theme, leave it empty or unset.
default_theme = ""

socials = [
    { name = "github", url = "https://github.com/amiraref/", icon = "github" },
    { name = "mastodon", url = "https://mas.to/@amiraref", icon = "mastodon" },
    { name = "linkedin", url = "https://linkedin.com/in/amiraref", icon = "linkedin" },
]

menu = [
    { name = "blog", url = "blog", trailing_slash = true },
    # { name = "archive", url = "archive", trailing_slash = true },
    { name = "tags", url = "tags", trailing_slash = true },
    # { name = "projects", url = "projects", trailing_slash = true },
]

email = "YW1pcmFyZWY4MDhAZ21haWwuY29t"

[extra.style]
# The custom background color.
# bg_color = ""

# The custom background color in dark mode.
# bg_dark_color = ""

# Enable header blur.
# header_blur = true

# The custom header color, only available when `header_blur` is false.
# header_color = ""

# The custom header color in dark mode, only available when `header_blur` is false.
# header_dark_color = ""

# The profile on home page.
[extra.profile]
name = "Amir Hasan Aref Asl"
bio = "i'm a python developer, linux user and also always will be a student"
# The URL of avatar.
avatar_url = "assets/amiraref-profile-2-square.jpg"
# Invert color in dark mode.
avatar_invert = false

# The social icons below the profile on the home page.
[[extra.profile.social]]
name = "github"
url = "https://github.com/amiraref"

[[extra.profile.social]]
name = "codeberg"
url = "https://codeberg.org/amiraref"

[[extra.profile.social]]
name = "stackoverflow"
url = "https://stackoverflow.com/users/15430200"

[[extra.profile.social]]
name = "linkedin"
url = "https://linkedin.com/in/amiraref"

[[extra.profile.social]]
name = "mastodon"
url = "https://mas.to/@amiraref"

[[extra.profile.social]]
name = "telegram"
url = "https://t.me/amir_720"

[[extra.profile.social]]
name = "email"
url = "mailto:amiraref808@gmail.com"

[[extra.profile.social]]
name = "rss"
url = "$BASE_URL/rss.xml"

# The top menu.
# [[extra.menu]]
# name = "Projects"
# url = "$BASE_URL/projects"

# [[extra.menu]]
# name = "Archive"
# url = "$BASE_URL/archive"

# [[extra.menu]]
# name = "Tags"
# url = "$BASE_URL/tags"

# [[extra.menu]]
# name = "About"
# url = "$BASE_URL/about"

# The page footer options.
[extra.footer]
since = 2024
# license = "CC BY-SA 4.0"
# license_url = "https://creativecommons.org/licenses/by-sa/4.0/deed"

# The giscus comment options, only available when comment is enabled.
[extra.giscus]
repo = ""
repo_id = ""
category = ""
category_id = ""
mapping = "pathname"
strict = 1
reactions_enabled = 0
emit_metadata = 0
input_position = "top"
theme = "light"
lang = "en"
loading = "lazy"
